# Generated by Django 6.0.2 on 2026-02-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='role',
            field=models.CharField(choices=[('examiner', 'Examiner'), ('coordinator', 'Coordinator')], default='examiner', max_length=20),
        ),
    ]
