# Generated by Django 6.0.2 on 2026-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_role_to_examiner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='role',
            field=models.CharField(choices=[('examiner', 'Examiner'), ('coordinator', 'Coordinator'), ('admin', 'Admin')], default='examiner', max_length=20),
        ),
    ]
