# Generated by Django 6.0.2 on 2026-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='examiner',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
