# Generated by Django 6.0.2 on 2026-02-19 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_soft_delete_to_examiner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stationscore',
            name='unique_student_station_examiner',
        ),
        migrations.AlterField(
            model_name='stationscore',
            name='examiner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
