# Generated by Django 6.0.2 on 2026-02-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_preserve_scores_on_examiner_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationscore',
            name='unlocked_for_correction',
            field=models.BooleanField(default=False),
        ),
    ]
