# Generated by Django 6.0.2 on 2026-02-20 11:27

import core.models.session
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_unlocked_for_correction_to_stationscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={'permissions': [('can_revert_session', 'Can revert completed session to scheduled')]},
        ),
        migrations.AlterField(
            model_name='sessionstudent',
            name='student_number',
            field=models.CharField(max_length=50, validators=[core.models.session.validate_student_number]),
        ),
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username_attempted', models.CharField(help_text='Username submitted in the login form', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address (X-Forwarded-For aware)', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser / device user-agent string')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp of the login attempt')),
                ('success', models.BooleanField(db_index=True, default=False, help_text='Whether the authentication attempt succeeded')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (null for failed attempts)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Audit Log',
                'verbose_name_plural': 'Login Audit Logs',
                'db_table': 'login_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='idx_login_audit_user_ts'), models.Index(fields=['ip_address', 'timestamp'], name='idx_login_audit_ip_ts'), models.Index(fields=['success', 'timestamp'], name='idx_login_audit_success_ts')],
            },
        ),
    ]
