# Generated by Django 5.2.11 on 2026-02-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='description',
        ),
    ]
