# Generated by Django 6.0.2 on 2026-02-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='examiner',
            name='financial_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
