# Generated by Django 5.2.11 on 2026-02-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_path_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examinerassignment',
            name='is_primary',
        ),
    ]
