# Generated by Django 5.2.11 on 2026-02-25 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_is_primary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={'permissions': [('can_revert_session', 'Can revert completed session to scheduled'), ('can_delete_session', 'Can archive/delete sessions')]},
        ),
    ]
