# Generated by Django 5.2.11 on 2026-02-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_can_delete_session_permission'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ilo',
            name='idx_ilo_course_active',
        ),
        migrations.RemoveField(
            model_name='ilo',
            name='active',
        ),
    ]
