# Generated by Django 5.2.11 on 2026-02-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_ilo_idx_ilo_course_active_remove_ilo_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
    ]
