# Generated by Django 5.2.11 on 2026-02-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_course_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final grade weight (e.g. 40 means the exam is marked out of 40 regardless of total station marks)', max_digits=6, null=True),
        ),
    ]
