# Generated by Django 5.2.11 on 2026-02-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_exam_exam_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='osce_mark',
            field=models.PositiveIntegerField(blank=True, help_text='Total OSCE mark for this course (entered manually, e.g. 50)', null=True),
        ),
    ]
