# Generated by Django 5.2.11 on 2026-02-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_course_osce_mark'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='path',
            name='unique_session_path_name_v2',
        ),
        migrations.AddConstraint(
            model_name='path',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('session', 'name'), name='unique_session_path_name_v2'),
        ),
    ]
