# Generated by Django 5.2.11 on 2026-02-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_path_unique_active_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='points',
            field=models.FloatField(default=1),
        ),
    ]
