# Generated by Django 5.2.11 on 2026-02-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_checklist_points_to_float'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistlibrary',
            name='suggested_points',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='dryquestion',
            name='points',
            field=models.FloatField(default=1),
        ),
    ]
