# Generated by Django 5.2.11 on 2026-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_points_to_float_library_dry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=120),
        ),
    ]
