# Generated by Django 5.2.11 on 2026-02-27 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_make_email_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionstudent',
            name='status',
            field=models.CharField(db_index=True, default='registered', max_length=20),
        ),
    ]
