# Generated by Django 5.2.11 on 2026-03-04 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_department_coordinator_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sessionstudent',
            name='idx_student_session_path',
        ),
        migrations.RemoveIndex(
            model_name='sessionstudent',
            name='idx_student_session_status',
        ),
        migrations.RemoveIndex(
            model_name='stationscore',
            name='idx_score_examiner_status',
        ),
        migrations.RemoveIndex(
            model_name='stationscore',
            name='idx_score_student_station',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department responsible for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='core.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='coordinator_position',
            field=models.CharField(blank=True, choices=[('head', 'Head'), ('rta', 'RTA'), ('organizer', 'Organizer')], default='', max_length=10),
        ),
    ]
