# Generated by Django 5.2.11 on 2026-03-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0027_rls_policies'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examiner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'coordinator'), _negated=True), ('coordinator_department__isnull', False), _connector='OR'), name='coordinator_must_have_department'),
        ),
        migrations.AddConstraint(
            model_name='examiner',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('role', 'coordinator'), _negated=True), models.Q(('coordinator_position', ''), _negated=True), _connector='OR'), name='coordinator_must_have_position'),
        ),
        migrations.AddConstraint(
            model_name='examiner',
            constraint=models.CheckConstraint(condition=models.Q(('role', 'coordinator'), models.Q(('coordinator_department__isnull', True), ('coordinator_position', '')), _connector='OR'), name='non_coordinator_no_dept_fields'),
        ),
    ]
