# Generated by Django 5.2.11 on 2026-03-04 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_coordinator_check_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('user_role', models.CharField(blank=True, default='', max_length=30)),
                ('department_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(default='SUCCESS', max_length=10)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(blank=True, default='', max_length=36)),
                ('resource_label', models.CharField(blank=True, default='', max_length=200)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log (Archived)',
                'verbose_name_plural': 'Audit Logs (Archived)',
                'db_table': 'audit_logs_archive',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='department_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Department ID for scoped access (nullable)', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_value',
            field=models.JSONField(blank=True, help_text='New state (for creates/updates)', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_value',
            field=models.JSONField(blank=True, help_text='Previous state (for updates/deletes)', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_method',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='resource_label',
            field=models.CharField(blank=True, default='', help_text='Human-readable name of the affected object', max_length=200),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('BLOCKED', 'Blocked'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_role',
            field=models.CharField(blank=True, default='', help_text='Role snapshot (examiner/coordinator/admin/superuser)', max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('SESSION_EXPIRED', 'Session Expired'), ('DEPT_CREATED', 'Department Created'), ('DEPT_UPDATED', 'Department Updated'), ('DEPT_DELETED', 'Department Deleted'), ('COORDINATOR_ASSIGNED', 'Coordinator Assigned'), ('COORDINATOR_REMOVED', 'Coordinator Removed'), ('COURSE_CREATED', 'Course Created'), ('COURSE_UPDATED', 'Course Updated'), ('COURSE_DELETED', 'Course Deleted'), ('EXAM_CREATED', 'Exam Created'), ('EXAM_UPDATED', 'Exam Updated'), ('EXAM_DELETED', 'Exam Deleted'), ('EXAM_PUBLISHED', 'Exam Published'), ('SESSION_CREATED', 'Session Created'), ('SESSION_UPDATED', 'Session Updated'), ('SESSION_DELETED', 'Session Deleted'), ('SESSION_STATUS_CHANGED', 'Session Status Changed'), ('PATH_CREATED', 'Path Created'), ('PATH_UPDATED', 'Path Updated'), ('PATH_DELETED', 'Path Deleted'), ('STATION_CREATED', 'Station Created'), ('STATION_UPDATED', 'Station Updated'), ('STATION_DELETED', 'Station Deleted'), ('STATION_ACCESSED', 'Station Accessed'), ('CHECKLIST_CREATED', 'Checklist Created'), ('CHECKLIST_UPDATED', 'Checklist Updated'), ('CHECKLIST_DELETED', 'Checklist Deleted'), ('SCORE_SUBMITTED', 'Score Submitted'), ('SCORE_AMENDED', 'Score Amended'), ('EXAMINER_ASSIGNED', 'Examiner Assigned'), ('EXAMINER_UNASSIGNED', 'Examiner Unassigned'), ('EXAMINER_ACCESS_BLOCKED', 'Examiner Access Blocked'), ('REPORT_VIEWED', 'Report Viewed'), ('REPORT_EXPORTED', 'Report Exported'), ('ADMIN_ACTION', 'Admin Action'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_type',
            field=models.CharField(db_index=True, max_length=50),
        ),
        # PostgreSQL cannot implicitly cast INTEGER → timestamptz.
        # Use to_timestamp() to convert the stored Unix epoch values.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        'ALTER TABLE audit_logs ALTER COLUMN "timestamp" '
                        'TYPE timestamp with time zone '
                        'USING to_timestamp("timestamp")'
                    ),
                    reverse_sql=(
                        'ALTER TABLE audit_logs ALTER COLUMN "timestamp" '
                        'TYPE integer '
                        'USING EXTRACT(epoch FROM "timestamp")::integer'
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='auditlog',
                    name='timestamp',
                    field=models.DateTimeField(auto_now_add=True, db_index=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='username',
            field=models.CharField(blank=True, default='', help_text='Snapshot of username at action time', max_length=150),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['department_id', 'timestamp'], name='idx_audit_dept_ts'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'timestamp'], name='idx_audit_action_ts'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status', 'timestamp'], name='idx_audit_status_ts'),
        ),
        migrations.AddField(
            model_name='auditlogarchive',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_archives', to=settings.AUTH_USER_MODEL),
        ),
    ]
