# Generated by Django 5.2.11 on 2026-03-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auditlogarchive_alter_auditlog_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
    ]
