# Generated by Django 5.2.11 on 2026-03-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='is_active',
        ),
    ]
