# Generated by Django 5.2.11 on 2026-03-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_department_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='is_critical',
        ),
        migrations.RemoveField(
            model_name='checklistlibrary',
            name='is_critical',
        ),
        migrations.RemoveField(
            model_name='stationscore',
            name='critical_items_failed',
        ),
        migrations.RemoveField(
            model_name='stationscore',
            name='passed_critical',
        ),
    ]
