# Generated by Django 5.2.11 on 2026-03-09 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_is_critical'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            # DB: drop tables with IF EXISTS safety (handles already-missing tables)
            database_operations=[
                migrations.RunSQL("DROP TABLE IF EXISTS dry_station_responses;", migrations.RunSQL.noop),
                migrations.RunSQL("DROP TABLE IF EXISTS mcq_options;", migrations.RunSQL.noop),
                migrations.RunSQL("DROP TABLE IF EXISTS dry_questions;", migrations.RunSQL.noop),
            ],
            # State: remove the models from Django's migration history
            state_operations=[
                migrations.DeleteModel(name='DryStationResponse'),
                migrations.DeleteModel(name='MCQOption'),
                migrations.DeleteModel(name='DryQuestion'),
            ],
        ),
    ]
