# Generated by Django 5.2.11 on 2026-03-09 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_dry_station'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionstudent',
            options={'permissions': [('can_view_student_list', 'Can view student lists')]},
        ),
    ]
