# Generated by Django 5.2.11 on 2026-03-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_sessionstudent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_dry',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
