# Generated by Django 5.2.11 on 2026-03-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_is_dry_to_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
    ]
