# Generated by Django 5.2.11 on 2026-03-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_image_to_checklistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemscore',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
