# Generated by Django 5.2.11 on 2026-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_expand_itemscore_notes_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationtemplate',
            name='is_dry',
            field=models.BooleanField(default=False),
        ),
    ]
