# Generated by Django 5.2.11 on 2026-03-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_add_is_dry_to_station_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='pass_threshold',
            field=models.PositiveIntegerField(default=70, help_text='Minimum percentage to pass this course (e.g. 70 means 70%)'),
        ),
    ]
