# Generated by Django 5.2.11 on 2026-03-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_course_pass_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_code',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
