# Generated by Django 5.2.11 on 2026-03-12 10:57

from django.db import migrations


def set_default_short_code(apps, schema_editor):
    """Set all empty short_codes to '0000'."""
    Course = apps.get_model('core', 'Course')
    Course.objects.filter(short_code='').update(short_code='0000')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_course_short_code_required'),
    ]

    operations = [
        migrations.RunPython(set_default_short_code),
    ]
