# Generated by Django 5.2.11 on 2026-03-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_rename_coordinator_department_to_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examiner',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='core.department'),
        ),
    ]
