# Generated by Django 5.2.11 on 2026-03-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_examiner_department'),
    ]

    operations = [
        # Column already exists in the DB (added manually).
        # This operation only updates Django's migration state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='examiner',
                    name='is_dry_user',
                    field=models.BooleanField(default=False),
                ),
            ],
            database_operations=[],
        ),
    ]
