# Generated by Django 5.2.11 on 2026-03-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_drop_unused_osce_tables'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examsession',
            options={'permissions': [('can_revert_session', 'Can revert completed session to scheduled'), ('can_delete_session', 'Can archive/delete sessions'), ('can_open_dry_grading', 'Can open dry grading for a session')]},
        ),
    ]
