# Generated by Django 5.2.11 on 2026-03-18 00:54
# Custom migration: uses SeparateDatabaseAndState to avoid index
# ownership issues on Azure PostgreSQL.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_add_allow_multi_login'),
    ]

    operations = [
        # ── session_key: db_index → unique ────────────────────────────
        # Use SeparateDatabaseAndState so Django doesn't try to DROP the
        # old index (which may be owned by a different DB role on Azure).
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Just add the unique constraint; the old plain index will
                # be superseded (Postgres is fine having both, and unique
                # implies an index).
                migrations.RunSQL(
                    sql='ALTER TABLE user_sessions ADD CONSTRAINT user_sessions_session_key_uniq UNIQUE (session_key)',
                    reverse_sql='ALTER TABLE user_sessions DROP CONSTRAINT IF EXISTS user_sessions_session_key_uniq',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='usersession',
                    name='session_key',
                    field=models.CharField(max_length=40, unique=True),
                ),
            ],
        ),
        # ── user: OneToOneField → ForeignKey ──────────────────────────
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # Drop the unique constraint on user_id (OneToOne enforces it)
                # and keep the FK. Django's OneToOneField = ForeignKey + unique.
                migrations.RunSQL(
                    sql='ALTER TABLE user_sessions DROP CONSTRAINT IF EXISTS user_sessions_user_id_key',
                    reverse_sql='ALTER TABLE user_sessions ADD CONSTRAINT user_sessions_user_id_key UNIQUE (user_id)',
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='usersession',
                    name='user',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='active_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
