# Generated by Django 5.2.11 on 2026-03-25 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_usersession_onetomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemscore',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_item_scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
