# Generated by Django 5.2.11 on 2026-03-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_add_graded_by_to_itemscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('SESSION_EXPIRED', 'Session Expired'), ('DEPT_CREATED', 'Department Created'), ('DEPT_UPDATED', 'Department Updated'), ('DEPT_DELETED', 'Department Deleted'), ('COORDINATOR_ASSIGNED', 'Coordinator Assigned'), ('COORDINATOR_REMOVED', 'Coordinator Removed'), ('COURSE_CREATED', 'Course Created'), ('COURSE_UPDATED', 'Course Updated'), ('COURSE_DELETED', 'Course Deleted'), ('EXAM_CREATED', 'Exam Created'), ('EXAM_UPDATED', 'Exam Updated'), ('EXAM_DELETED', 'Exam Deleted'), ('EXAM_PUBLISHED', 'Exam Published'), ('SESSION_CREATED', 'Session Created'), ('SESSION_UPDATED', 'Session Updated'), ('SESSION_DELETED', 'Session Deleted'), ('SESSION_STATUS_CHANGED', 'Session Status Changed'), ('PATH_CREATED', 'Path Created'), ('PATH_UPDATED', 'Path Updated'), ('PATH_DELETED', 'Path Deleted'), ('STATION_CREATED', 'Station Created'), ('STATION_UPDATED', 'Station Updated'), ('STATION_DELETED', 'Station Deleted'), ('STATION_ACCESSED', 'Station Accessed'), ('CHECKLIST_CREATED', 'Checklist Created'), ('CHECKLIST_UPDATED', 'Checklist Updated'), ('CHECKLIST_DELETED', 'Checklist Deleted'), ('SCORE_SUBMITTED', 'Score Submitted'), ('SCORE_AMENDED', 'Score Amended'), ('EXAMINER_ASSIGNED', 'Examiner Assigned'), ('EXAMINER_UNASSIGNED', 'Examiner Unassigned'), ('EXAMINER_ACCESS_BLOCKED', 'Examiner Access Blocked'), ('REPORT_VIEWED', 'Report Viewed'), ('REPORT_EXPORTED', 'Report Exported'), ('STUDENT_ADDED', 'Student Added'), ('STUDENT_REMOVED', 'Student Removed'), ('STUDENT_PATH_ASSIGNED', 'Student Path Assigned'), ('STUDENT_BULK_IMPORT', 'Student Bulk Import'), ('EXAMINER_CREATED', 'Examiner Created'), ('EXAMINER_UPDATED', 'Examiner Updated'), ('EXAMINER_DELETED', 'Examiner Deleted'), ('EXAMINER_RESTORED', 'Examiner Restored'), ('EXAMINER_BULK_IMPORT', 'Examiner Bulk Import'), ('TEMPLATE_CREATED', 'Template Created'), ('TEMPLATE_UPDATED', 'Template Updated'), ('TEMPLATE_DELETED', 'Template Deleted'), ('TEMPLATE_APPLIED', 'Template Applied'), ('SESSION_ACTIVATED', 'Session Activated'), ('SESSION_DEACTIVATED', 'Session Deactivated'), ('SESSION_FINISHED', 'Session Finished'), ('SESSION_COMPLETED', 'Session Completed'), ('SESSION_RESTORED', 'Session Restored'), ('SESSION_REVERTED', 'Session Reverted'), ('EXAM_COMPLETED', 'Exam Completed'), ('EXAM_REVERTED', 'Exam Reverted'), ('EXAM_ARCHIVED', 'Exam Archived'), ('EXAM_RESTORED', 'Exam Restored'), ('BULK_OPERATION', 'Bulk Operation'), ('DATA_EXPORT', 'Data Export'), ('ADMIN_ACTION', 'Admin Action'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt')], db_index=True, max_length=30),
        ),
    ]
