# Generated by Django 5.2.11 on 2026-03-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_audit_trail_expanded_action_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'default_permissions': ('add', 'view'), 'ordering': ['-timestamp'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='auditlogarchive',
            options={'default_permissions': ('add', 'view'), 'ordering': ['-timestamp'], 'verbose_name': 'Audit Log (Archived)', 'verbose_name_plural': 'Audit Logs (Archived)'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='checksum',
            field=models.CharField(blank=True, default='', editable=False, help_text='SHA-256 checksum for tamper detection', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlogarchive',
            name='checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login Success'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('SESSION_EXPIRED', 'Session Expired'), ('DEPT_CREATED', 'Department Created'), ('DEPT_UPDATED', 'Department Updated'), ('DEPT_DELETED', 'Department Deleted'), ('COORDINATOR_ASSIGNED', 'Coordinator Assigned'), ('COORDINATOR_REMOVED', 'Coordinator Removed'), ('COURSE_CREATED', 'Course Created'), ('COURSE_UPDATED', 'Course Updated'), ('COURSE_DELETED', 'Course Deleted'), ('EXAM_CREATED', 'Exam Created'), ('EXAM_UPDATED', 'Exam Updated'), ('EXAM_DELETED', 'Exam Deleted'), ('EXAM_PUBLISHED', 'Exam Published'), ('SESSION_CREATED', 'Session Created'), ('SESSION_UPDATED', 'Session Updated'), ('SESSION_DELETED', 'Session Deleted'), ('SESSION_STATUS_CHANGED', 'Session Status Changed'), ('PATH_CREATED', 'Path Created'), ('PATH_UPDATED', 'Path Updated'), ('PATH_DELETED', 'Path Deleted'), ('STATION_CREATED', 'Station Created'), ('STATION_UPDATED', 'Station Updated'), ('STATION_DELETED', 'Station Deleted'), ('STATION_ACCESSED', 'Station Accessed'), ('CHECKLIST_CREATED', 'Checklist Created'), ('CHECKLIST_UPDATED', 'Checklist Updated'), ('CHECKLIST_DELETED', 'Checklist Deleted'), ('SCORE_SUBMITTED', 'Score Submitted'), ('SCORE_UPDATED', 'Score Updated'), ('SCORE_AMENDED', 'Score Amended'), ('SCORE_BULK_SUBMITTED', 'Score Bulk Submitted'), ('GRADING_SESSION_STARTED', 'Grading Session Started'), ('GRADING_SESSION_COMPLETED', 'Grading Session Completed'), ('GRADING_SESSION_ABANDONED', 'Grading Session Abandoned'), ('CHECKLIST_SCORE_DELETED', 'Checklist Score Deleted'), ('EXAMINER_ASSIGNED', 'Examiner Assigned'), ('EXAMINER_UNASSIGNED', 'Examiner Unassigned'), ('EXAMINER_ACCESS_BLOCKED', 'Examiner Access Blocked'), ('REPORT_VIEWED', 'Report Viewed'), ('REPORT_EXPORTED', 'Report Exported'), ('STUDENT_ADDED', 'Student Added'), ('STUDENT_REMOVED', 'Student Removed'), ('STUDENT_PATH_ASSIGNED', 'Student Path Assigned'), ('STUDENT_BULK_IMPORT', 'Student Bulk Import'), ('EXAMINER_CREATED', 'Examiner Created'), ('EXAMINER_UPDATED', 'Examiner Updated'), ('EXAMINER_DELETED', 'Examiner Deleted'), ('EXAMINER_RESTORED', 'Examiner Restored'), ('EXAMINER_BULK_IMPORT', 'Examiner Bulk Import'), ('TEMPLATE_CREATED', 'Template Created'), ('TEMPLATE_UPDATED', 'Template Updated'), ('TEMPLATE_DELETED', 'Template Deleted'), ('TEMPLATE_APPLIED', 'Template Applied'), ('SESSION_ACTIVATED', 'Session Activated'), ('SESSION_DEACTIVATED', 'Session Deactivated'), ('SESSION_FINISHED', 'Session Finished'), ('SESSION_COMPLETED', 'Session Completed'), ('SESSION_RESTORED', 'Session Restored'), ('SESSION_REVERTED', 'Session Reverted'), ('EXAM_COMPLETED', 'Exam Completed'), ('EXAM_REVERTED', 'Exam Reverted'), ('EXAM_ARCHIVED', 'Exam Archived'), ('EXAM_RESTORED', 'Exam Restored'), ('EXAM_START_VERIFY_ATT', 'Exam Start Verification Attempt'), ('EXAM_START_VERIFY_OK', 'Exam Start Verification Success'), ('MASTER_KEY_VERIFY_ATT', 'Master Key Verification Attempt'), ('MASTER_KEY_VERIFY_OK', 'Master Key Verification Success'), ('AUDIT_LOG_VIEWED', 'Audit Log Viewed'), ('AUDIT_LOG_SEARCHED', 'Audit Log Searched'), ('AUDIT_LOG_EXPORTED', 'Audit Log Exported'), ('BULK_OPERATION', 'Bulk Operation'), ('DATA_EXPORT', 'Data Export'), ('ADMIN_ACTION', 'Admin Action'), ('UNAUTHORIZED_ACCESS', 'Unauthorized Access Attempt'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('RATE_LIMIT_HIT', 'Rate Limit Hit'), ('TOKEN_VALIDATION_FAILED', 'Token Validation Failed')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('BLOCKED', 'Blocked'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='SUCCESS', max_length=10),
        ),
    ]
